modLoader="javafml"
loaderVersion="[54,)"
license="GNU GPLv3"
issueTrackerURL="${github}/issues"
[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="${github}"
logoFile="icon.png"
authors="${author}, pop4959"
description="${description}"
[[mixins]]
config="chunksmith.mixins.json"
[[dependencies.${id}]]
    modId="forge"
    mandatory=true
    versionRange="[54,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.4,1.21.5)"
    ordering="NONE"
    side="BOTH"
