org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=false
group=com.kishku7
artifactName=Chunksmith
version=4.3.6
description=Pre-generates chunks, quickly, efficiently, and safely
github=https://github.com/Kishku7/Chunksmith
author=Kishku7
modId=chunksmith
mcVersion=26.3-pre-1
fabricApiVersion=0.159.1+26.3
