modLoader="javafml"
loaderVersion="[56,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/Kishku7/mod_support/issues"
[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="${github}"
logoFile="icon.png"
authors="${author}, pop4959"
description="${description}"
[[mixins]]
config="chunksmith.mixins.json"
[[dependencies.${id}]]
    modId="forge"
    mandatory=true
    versionRange="[56,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.6,1.21.9)"
    ordering="NONE"
    side="BOTH"
