"""Chunksmith -- make published/self-built voxy jars consumable by an older cell's Loom.

Run once after dropping the soft-dep jars into libs/:

    python scripts/prep-libs.py

WHY THIS EXISTS
---------------
MC lines that need Loom 1.13.x-1.12.x (pre-26, obfuscated) flatly refuse a mod dependency stamped
with a Loom NEWER than themselves -- at configure time, before a line is compiled: "Mod was built
with a newer version of Loom (1.16.2), you are using Loom (1.13.6)" -- even though the jar's actual
class content (remapped from `Fabric-Mapping-Namespace: intermediary`) is perfectly readable by the
older Loom. Squarely a Loom-metadata problem, not a code problem.

WHAT THIS DOES
--------------
For each (SRC, DST) pair below, writes libs/DST: a byte-for-byte copy of libs/SRC with the single
`Fabric-Loom-Version` manifest line dropped. That line is a build-provenance stamp and is used for
nothing else; `Fabric-Mapping-Namespace: intermediary` -- the line that actually tells Loom to remap
the jar from intermediary into our dev mappings -- is left exactly as it is. No class is touched.

Every derived jar is compileOnly and NEVER shipped (voxy and its forks are All-Rights-Reserved),
lives in the gitignored libs/, and is regenerated by re-running this script.

Jars that are mojmap-native (the 26.x line; NeoForge cells in general) need none of this -- Loom/
ModDevGradle reads them directly, so they are not listed here.

JARS HANDLED
------------
- voxy-0.2.16-beta+1.21.11.jar (upstream, Fabric 1.21.11 cell; Loom 1.13.6 there vs 1.16.2 stamped)
- voxy-0.2.15-beta+1.21.1-m3t4f1v3-fabric.jar (m3t4f1v3 fork, Fabric 1.21.1 cell; Loom 1.12.7 there
  vs 1.16.2 stamped -- same trap, self-built 2026-08-03 from github.com/m3t4f1v3/voxy `multiversion`
  branch since upstream never published a 1.21.1 voxy build on any loader; see
  Memory/minecraft/lod-ecosystem.md and _codegen/compat.py::has_voxy())
"""
import os
import shutil
import sys
import zipfile

LIBS = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "libs")
STRIP = "Fabric-Loom-Version"

JARS = [
    ("voxy-0.2.16-beta+1.21.11.jar", "voxy-0.2.16-beta+1.21.11-loomcompat.jar"),
    ("voxy-0.2.15-beta+1.21.1-m3t4f1v3-fabric.jar", "voxy-0.2.15-beta+1.21.1-m3t4f1v3-fabric-loomcompat.jar"),
]


def strip_loom_stamp(src_name, dst_name):
    src = os.path.join(LIBS, src_name)
    dst = os.path.join(LIBS, dst_name)
    if not os.path.exists(src):
        print("skip: missing %s -- put it in libs/ first" % src_name)
        return False

    tmp = dst + ".part"
    with zipfile.ZipFile(src) as zin, zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            data = zin.read(item.filename)
            if item.filename == "META-INF/MANIFEST.MF":
                lines = data.decode("utf-8").splitlines()
                kept = [ln for ln in lines if not ln.startswith(STRIP + ":")]
                if len(kept) == len(lines):
                    print("note: %s carried no %s line; copying as-is" % (src_name, STRIP))
                data = ("\r\n".join(kept) + "\r\n").encode("utf-8")
            zout.writestr(item, data)
    shutil.move(tmp, dst)
    print("wrote libs/%s (%s stripped)" % (dst_name, STRIP))
    return True


def main():
    ok = True
    for src_name, dst_name in JARS:
        if not strip_loom_stamp(src_name, dst_name):
            ok = False
    if not ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
