"""Chunksmith -- make the published voxy 1.21.11 jar consumable by the 1.21.11 cell's Loom.

Run once after dropping the soft-dep jars into libs/:

    python scripts/prep-libs.py

WHY THIS EXISTS
---------------
MC 1.21.11 needs Loom 1.13.x (Loom 1.16 flatly refuses it: "Cannot use Mojang mappings in a
non-obfuscated environment" -- it assumes the 26 line, where Minecraft ships unobfuscated). But the
PUBLISHED voxy-0.2.16-beta+1.21.11 jar was itself built with Loom 1.16.2 and says so in its manifest:

    Fabric-Loom-Version: 1.16.2
    Fabric-Mapping-Namespace: intermediary

and Loom hard-refuses any mod dependency stamped with a Loom NEWER than itself -- at configure time,
before a line is compiled: "Mod was built with a newer version of Loom (1.16.2), you are using Loom
(1.13.6)". So the one pre-26 cell that has a real voxy adapter is the one cell that cannot have the
toolchain to read voxy. Squarely a Loom-metadata problem, not a code problem.

WHAT THIS DOES
--------------
Writes libs/voxy-0.2.16-beta+1.21.11-loomcompat.jar: a byte-for-byte copy of the upstream jar with the
single `Fabric-Loom-Version` manifest line dropped. That line is a build-provenance stamp and is used
for nothing else; `Fabric-Mapping-Namespace: intermediary` -- the line that actually tells Loom to remap
the jar from intermediary into our dev mappings -- is left exactly as it is. No class is touched.

The derived jar is compileOnly and NEVER shipped (voxy is All-Rights-Reserved), lives in the gitignored
libs/, and is regenerated by re-running this script.

The 26.x voxy jar needs none of this: it is mojmap-native and Loom 1.16 reads it directly.
"""
import os
import shutil
import sys
import zipfile

LIBS = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "libs")
SRC = "voxy-0.2.16-beta+1.21.11.jar"
DST = "voxy-0.2.16-beta+1.21.11-loomcompat.jar"
STRIP = "Fabric-Loom-Version"


def main():
    src = os.path.join(LIBS, SRC)
    dst = os.path.join(LIBS, DST)
    if not os.path.exists(src):
        sys.exit("missing %s -- put the published voxy 1.21.11 jar in libs/ first" % SRC)

    tmp = dst + ".part"
    with zipfile.ZipFile(src) as zin, zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            data = zin.read(item.filename)
            if item.filename == "META-INF/MANIFEST.MF":
                lines = data.decode("utf-8").splitlines()
                kept = [ln for ln in lines if not ln.startswith(STRIP + ":")]
                if len(kept) == len(lines):
                    print("note: %s carried no %s line; copying as-is" % (SRC, STRIP))
                data = ("\r\n".join(kept) + "\r\n").encode("utf-8")
            zout.writestr(item, data)
    shutil.move(tmp, dst)
    print("wrote libs/%s (%s stripped)" % (DST, STRIP))


if __name__ == "__main__":
    main()
