modLoader="javafml"
loaderVersion="[2,)"
license="GNU GPLv3"
issueTrackerURL="${github}/issues"
[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
displayURL="${github}"
logoFile="icon.png"
authors="${author}, pop4959"
description="${description}"
[[mixins]]
config="chunksmith.mixins.json"
[[dependencies.chunksmith]]
   modId="neoforge"
   type="required"
   versionRange="[20.4,20.5)"
   ordering="NONE"
   side="BOTH"
[[dependencies.chunksmith]]
   modId="minecraft"
   type="required"
   versionRange="[1.20.2,1.20.5)"
   ordering="NONE"
   side="BOTH"
